name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        
      - name: Write tfvars file from secret
        run: echo "${{ secrets.TF_VARS_CONTENT }}" > terraform.tfvars

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -var-file="terraform.tfvars" -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -var-file="terraform.tfvars" -auto-approve
          else
            echo "Invalid action selected: ${{ github.event.inputs.action }}"
            exit 1
          fi
